[RUN_SETTINGS]
; --------------------------------------------------
;  各処理の実行フラグ (on = 実行する / off = 実行しない)
; --------------------------------------------------

; TLEのMRAM変更コマンドの自動生成
TLE_MRAM = off

; グラフの自動生成
process_B = off

; 報告用PDFの出力
process_C = on